import { Link } from "react-router-dom";
import { ArrowRight, BarChart3, Database, FileText, LockKeyhole, Mail, ShieldCheck, UserRoundCheck } from "lucide-react";
import { ServiceMotionBackdrop } from "../components/ServiceMotion";
import "./premium-pages.css";

const sections = [
  { icon: Database, title: "Information we collect", body: "We collect information you choose to provide through contact, growth-assessment and career forms. This can include your name, company, email, phone number, service interests, project details, career preferences and a resume, LinkedIn or portfolio link. Our hosting and security providers may also process basic device, browser, IP-address and request information needed to deliver and protect the website." },
  { icon: UserRoundCheck, title: "How we use information", body: "We use submitted information to respond to enquiries, route requests to the relevant Timex capability, prepare proposals, review career applications, deliver requested services, maintain business records and protect the website from spam, fraud or misuse. We do not use a career application to make decisions unrelated to recruitment." },
  { icon: FileText, title: "Forms, booking and payments", body: "Website forms may be delivered through an approved form-processing provider. Booking links may open a scheduling provider. Approved payments are processed through Square or another disclosed payment provider. Timex does not intentionally store full payment-card details on this website. Those providers process information under their own privacy terms." },
  { icon: BarChart3, title: "Analytics and measurement", body: "If you accept analytics, this website may load Google Analytics through Google Tag Manager, Meta Pixel and Microsoft Clarity. These tools help us understand page visits, campaign performance, form outcomes and aggregated interaction patterns such as heatmaps. They may process device, browser, page, referral and interaction information under their own terms. If you decline, these optional tools are not loaded." },
  { icon: ShieldCheck, title: "Sharing and service providers", body: "We may share information with team members and service providers who need it to respond, deliver, host, secure, schedule or support the requested work. We may also disclose information when required by law or when reasonably necessary to protect users, Timex or others. We do not sell personal information for money." },
  { icon: LockKeyhole, title: "Retention and safeguards", body: "We retain information only as long as reasonably needed for the purpose described, business records, dispute resolution and applicable legal obligations. We use reasonable administrative and technical safeguards, but no website or electronic transmission can be guaranteed completely secure." },
  { icon: Mail, title: "Your choices and requests", body: "You may ask to access, correct or delete information you submitted, subject to applicable law and legitimate record-keeping needs. You may also ask us to stop non-essential communications. Send privacy requests to team@timexsolutioninc.com and include enough detail for us to understand and verify the request." },
];

export default function PrivacyPolicy() {
  return (
    <main className="premium-page min-h-screen pt-28 sm:pt-32">
      <ServiceMotionBackdrop />
      <section className="premium-section pt-16 sm:pt-20" aria-labelledby="privacy-title"><div className="premium-shell relative z-10"><p className="premium-kicker">Privacy notice</p><h1 id="privacy-title" className="premium-display max-w-5xl">Clear information about <span className="premium-display-gradient">your information.</span></h1><p className="premium-copy mt-7">This notice explains how Timex Solution Inc handles information submitted through this website and related business conversations. Timex Solution Inc is based in Fresno, California.</p><div className="mt-8 flex flex-wrap gap-3"><span className="premium-tag">Effective August 31, 2026</span><a href="mailto:team@timexsolutioninc.com" className="premium-tag hover:border-purple-300/30 hover:text-white">team@timexsolutioninc.com</a></div></div></section>

      <section className="premium-section pt-8" aria-label="Privacy policy details"><div className="premium-shell relative z-10 grid gap-5 md:grid-cols-2">{sections.map(({ icon: Icon, title, body }, index) => <article key={title} className="premium-panel p-7 sm:p-8"><div className="flex items-center justify-between"><span className="premium-icon-shell"><Icon className="h-7 w-7" /></span><span className="text-4xl text-white/[0.08]">0{index + 1}</span></div><h2 className="mt-7 text-2xl text-white">{title}</h2><p className="mt-4 text-sm leading-7 text-gray-400 sm:text-base">{body}</p></article>)}</div></section>

      <section className="premium-section pt-6"><div className="premium-shell relative z-10 grid gap-5 lg:grid-cols-2"><article className="premium-panel p-7 sm:p-9"><p className="premium-kicker">External links</p><h2 className="mt-5 text-3xl text-white">Other websites have their own terms.</h2><p className="mt-4 text-sm leading-7 text-gray-400 sm:text-base">This website may link to client sites, social platforms, scheduling providers and other third parties. Their privacy practices are controlled by them, not by this notice.</p></article><article className="premium-panel p-7 sm:p-9"><p className="premium-kicker">Policy updates</p><h2 className="mt-5 text-3xl text-white">The revision date will stay visible.</h2><p className="mt-4 text-sm leading-7 text-gray-400 sm:text-base">When this notice materially changes, the effective date above will be updated. It does not automatically change each time someone opens the page.</p></article></div></section>

      <section className="premium-section pt-8"><div className="premium-shell relative z-10"><div className="premium-panel p-8 text-center sm:p-12"><ShieldCheck className="mx-auto h-8 w-8 text-PurpleLight" /><h2 className="premium-heading mx-auto mt-5">Have a privacy question or <span className="premium-heading-gradient">data request?</span></h2><p className="premium-copy mx-auto mt-6">Contact the Timex team and describe the information or website interaction your request concerns.</p><div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row"><a href="mailto:team@timexsolutioninc.com" className="premium-button">Email the Privacy Contact <ArrowRight className="h-4 w-4" /></a><Link to="/contact" className="premium-button premium-button--secondary">Contact Page</Link></div></div></div></section>
    </main>
  );
}
